export const personaggi = [
  {
    id: 1,
    nome: "Goblin",
    taglia: "Piccola",
    tipo: "Mostroide",
    allineamento: "Caotico Malvagio",
    classeArmatura: "15 (cuoio e agilità)",
  },
  {
    id: 2,
    nome: "Orco",
    taglia: "Media",
    tipo: "Umanoide",
    allineamento: "Caotico Neutrale",
    classeArmatura: "13 (pelle naturale)",
  },
  {
    id: 3,
    nome: "Troll",
    taglia: "Grande",
    tipo: "Gigante",
    allineamento: "Caotico Malvagio",
    classeArmatura: "15 (rigenerazione)",
  },
  {
    id: 4,
    nome: "Drago Rosso Giovane",
    taglia: "Grande",
    tipo: "Drago",
    allineamento: "Caotico Malvagio",
    classeArmatura: "18 (scaglie naturali)",
  },
  {
    id: 5,
    nome: "Scheletro",
    taglia: "Media",
    tipo: "Non Morto",
    allineamento: "Legale Malvagio",
    classeArmatura: "13 (armatura leggera)",
  },
  {
    id: 6,
    nome: "Zombi",
    taglia: "Media",
    tipo: "Non Morto",
    allineamento: "Neutrale Malvagio",
    classeArmatura: "8 (senza armatura)",
  },
  {
    id: 7,
    nome: "Gnoll",
    taglia: "Media",
    tipo: "Umanoide",
    allineamento: "Caotico Malvagio",
    classeArmatura: "14 (cuoio e scudo)",
  },
  {
    id: 8,
    nome: "Cubo Gelatinoso",
    taglia: "Grande",
    tipo: "Melma",
    allineamento: "Non allineato",
    classeArmatura: "6 (gelatinosa)",
  },
  {
    id: 9,
    nome: "Mimic",
    taglia: "Media",
    tipo: "Mostroide",
    allineamento: "Neutrale",
    classeArmatura: "12 (forma mimetica)",
  },
  {
    id: 10,
    nome: "Lupo Infernale",
    taglia: "Grande",
    tipo: "Bestia Magica",
    allineamento: "Legale Malvagio",
    classeArmatura: "15 (pelle resistente)",
  },
  {
    id: 11,
    nome: "Elementale del Fuoco",
    taglia: "Grande",
    tipo: "Elementale",
    allineamento: "Neutrale",
    classeArmatura: "13 (fiamme vive)",
  },
  {
    id: 12,
    nome: "Beholder",
    taglia: "Grande",
    tipo: "Aberrazione",
    allineamento: "Legale Malvagio",
    classeArmatura: "18 (carapace)",
  },
  {
    id: 13,
    nome: "Lich",
    taglia: "Media",
    tipo: "Non Morto",
    allineamento: "Neutrale Malvagio",
    classeArmatura: "17 (protezione magica)",
  },
  {
    id: 14,
    nome: "Arpia",
    taglia: "Media",
    tipo: "Mostroide",
    allineamento: "Caotico Malvagio",
    classeArmatura: "11 (piume)",
  },
  {
    id: 15,
    nome: "Golem di Pietra",
    taglia: "Grande",
    tipo: "Costrutto",
    allineamento: "Non allineato",
    classeArmatura: "17 (corazza di pietra)",
  },
  {
    id: 16,
    nome: "Basilisco",
    taglia: "Media",
    tipo: "Bestia Magica",
    allineamento: "Neutrale",
    classeArmatura: "15 (scaglie)",
  },
  {
    id: 17,
    nome: "Drider",
    taglia: "Grande",
    tipo: "Aberrazione",
    allineamento: "Caotico Malvagio",
    classeArmatura: "19 (chitina)",
  },
  {
    id: 18,
    nome: "Spettro",
    taglia: "Media",
    tipo: "Non Morto",
    allineamento: "Caotico Malvagio",
    classeArmatura: "12 (etereo)",
  },
  {
    id: 19,
    nome: "Naga Spirituale",
    taglia: "Grande",
    tipo: "Aberrazione",
    allineamento: "Neutrale Malvagio",
    classeArmatura: "16 (scaglie mistiche)",
  },
  {
    id: 20,
    nome: "Roc",
    taglia: "Enorme",
    tipo: "Bestia",
    allineamento: "Neutrale",
    classeArmatura: "15 (piumaggio spesso)",
  },
];
